//
//  SearchStationsModels.swift
//  TrainTicketMachine
//
//  Created by João Gameiro on 28/03/18.
//  Copyright (c) 2018 JG.com. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/**
 Search Stations Use Cases
 
 ````
 case FetchStationsList
 case FilterStationsList
 case MatchingLettersForFilteredResults
 ````
 */

enum SearchStations {
    /// Contains structs representing the Request, Response and ViewModel for the FetchStationsList use case.
    enum FetchStationsList {
        struct Request {
        }
        struct Response {
            var stations: [Station]
        }
        struct ViewModel {
            struct DisplayedStation {
                var name: String
            }
            var displayedStation: [DisplayedStation]
        }
    }
    /// Contains structs representing the Request, Response and ViewModel for the FilterStationsList use case.
    enum FilterStationsList {
        struct Request {
            let stationsList: [SearchStations.FetchStationsList.ViewModel.DisplayedStation]
            let textInput: String
        }
        struct Response {
            var filteredStations: [SearchStations.FetchStationsList.ViewModel.DisplayedStation]
        }
        struct ViewModel {
            struct DisplayedFilteredStation {
                var name: String
            }
            var displayedFilteredStation: [DisplayedFilteredStation]
        }
    }
    /// Contains structs representing the Request, Response and ViewModel for the MatchingLettersForFilteredResults use case.
    enum MatchingLettersForFilteredResults {
        struct Request {
            let filteredResults: [SearchStations.FilterStationsList.ViewModel.DisplayedFilteredStation]
            let textToTrim: String
        }
        struct Response {
            var matchingLettersList: [String]
        }
        struct ViewModel {
            var matchingLettersList: [String]
        }
    }
}
