//
//  SearchStationsPresenter.swift
//  TrainTicketMachine
//
//  Created by João Gameiro on 28/03/18.
//  Copyright (c) 2018 JG.com. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchStationsPresentationLogic {
    func presentStationsList(response: SearchStations.FetchStationsList.Response)
    func presentFilteredStationsList(response: SearchStations.FilterStationsList.Response)
    func presentMatchingLettersForResultsList(response: SearchStations.MatchingLettersForFilteredResults.Response)
}

class SearchStationsPresenter: SearchStationsPresentationLogic {
    weak var viewController: SearchStationsDisplayLogic?
    
    // MARK: Present Stations List
    /**
     Prepare the list of stations sent by the interactor to be displayed by the viewcontroller.
     */
    func presentStationsList(response: SearchStations.FetchStationsList.Response) {
        var displayedStations : [SearchStations.FetchStationsList.ViewModel.DisplayedStation] = []
        for station in response.stations {
            let displayStation = SearchStations.FetchStationsList.ViewModel.DisplayedStation(name: station.name)
            displayedStations.append(displayStation)
        }
        let viewModel = SearchStations.FetchStationsList.ViewModel(displayedStation: displayedStations)
        viewController?.displayStationsList(viewModel: viewModel)
    }
    // MARK: Present Filtered Stations List
    /**
     Prepare the filtered list of stations sent by the interactor to be displayed by the viewcontroller.
     */
    func presentFilteredStationsList(response: SearchStations.FilterStationsList.Response) {
        var displayedFilteredStations : [SearchStations.FilterStationsList.ViewModel.DisplayedFilteredStation] = []
        for filteredStation in response.filteredStations {
            let displayFilteredStation = SearchStations.FilterStationsList.ViewModel.DisplayedFilteredStation(name: filteredStation.name)
            displayedFilteredStations.append(displayFilteredStation)
        }
        let viewModel = SearchStations.FilterStationsList.ViewModel(displayedFilteredStation: displayedFilteredStations)
        viewController?.displayFilteredStationsList(viewModel: viewModel)
    }
    // MARK: Present Matching Letters For Filtered Stations List
    /**
     Prepare the list of matching letters sent by the interactor to be displayed by the viewcontroller.
     */
    func presentMatchingLettersForResultsList(response: SearchStations.MatchingLettersForFilteredResults.Response) {
        let viewModel = SearchStations.MatchingLettersForFilteredResults.ViewModel(matchingLettersList: response.matchingLettersList)
        viewController?.displayMatchingLettersForResultsList(viewModel: viewModel)
    }
}
